import Joi from 'joi';

export const staffValidators = {
  create: Joi.object({
    employee_id: Joi.string().required(),
    first_name: Joi.string().required(),
    middle_name: Joi.string().allow('', null),
    last_name: Joi.string().required(),
    date_of_birth: Joi.date().required(),
    gender: Joi.string().valid('male', 'female', 'other').required(),
    blood_group: Joi.string().allow('', null),
    nationality: Joi.string().default('Indian'),
    religion: Joi.string().allow('', null),
    category: Joi.string().valid('general', 'obc', 'sc', 'st', 'other').allow('', null),
    marital_status: Joi.string().valid('single', 'married', 'divorced', 'widowed').allow('', null),
    email: Joi.string().email().required(),
    phone: Joi.string().required(),
    alternate_phone: Joi.string().allow('', null),
    aadhar_number: Joi.string().length(12).allow('', null),
    pan_number: Joi.string().length(10).allow('', null),
    address: Joi.string().allow('', null),
    city: Joi.string().allow('', null),
    state: Joi.string().allow('', null),
    pincode: Joi.string().allow('', null),
    staff_type: Joi.string().valid('teaching', 'non-teaching', 'administrative', 'support').required(),
    designation: Joi.string().required(),
    department: Joi.string().allow('', null),
    date_of_joining: Joi.date().required(),
    employment_type: Joi.string().valid('permanent', 'contract', 'temporary', 'part-time').required(),
    status: Joi.string().valid('active', 'on-leave', 'suspended', 'resigned', 'retired').default('active'),
    highest_qualification: Joi.string().allow('', null),
    qualifications: Joi.array().items(Joi.object({
      degree: Joi.string().required(),
      institution: Joi.string().required(),
      year: Joi.number().required(),
      specialization: Joi.string().allow('', null)
    })).default([]),
    specialization: Joi.string().allow('', null),
    experience_years: Joi.number().min(0).allow(null),
    previous_experience: Joi.string().allow('', null),
    basic_salary: Joi.number().min(0).allow(null),
    gross_salary: Joi.number().min(0).allow(null),
    bank_name: Joi.string().allow('', null),
    bank_account_number: Joi.string().allow('', null),
    bank_ifsc: Joi.string().allow('', null),
    pf_number: Joi.string().allow('', null),
    esi_number: Joi.string().allow('', null),
    photo_url: Joi.string().allow('', null),
    resume_url: Joi.string().allow('', null),
    documents: Joi.array().items(Joi.object({
      type: Joi.string().required(),
      url: Joi.string().required(),
      name: Joi.string().required()
    })).default([]),
    emergency_contact_name: Joi.string().allow('', null),
    emergency_contact_phone: Joi.string().allow('', null),
    emergency_contact_relation: Joi.string().allow('', null),
    medical_conditions: Joi.string().allow('', null),
    allergies: Joi.string().allow('', null),
    subjects_can_teach: Joi.array().items(Joi.string()).default([]),
    notes: Joi.string().allow('', null)
  }),

  update: Joi.object({
    first_name: Joi.string(),
    middle_name: Joi.string().allow('', null),
    last_name: Joi.string(),
    date_of_birth: Joi.date(),
    gender: Joi.string().valid('male', 'female', 'other'),
    blood_group: Joi.string().allow('', null),
    nationality: Joi.string(),
    religion: Joi.string().allow('', null),
    category: Joi.string().valid('general', 'obc', 'sc', 'st', 'other').allow('', null),
    marital_status: Joi.string().valid('single', 'married', 'divorced', 'widowed').allow('', null),
    email: Joi.string().email(),
    phone: Joi.string(),
    alternate_phone: Joi.string().allow('', null),
    aadhar_number: Joi.string().length(12).allow('', null),
    pan_number: Joi.string().length(10).allow('', null),
    address: Joi.string().allow('', null),
    city: Joi.string().allow('', null),
    state: Joi.string().allow('', null),
    pincode: Joi.string().allow('', null),
    staff_type: Joi.string().valid('teaching', 'non-teaching', 'administrative', 'support'),
    designation: Joi.string(),
    department: Joi.string().allow('', null),
    date_of_joining: Joi.date(),
    employment_type: Joi.string().valid('permanent', 'contract', 'temporary', 'part-time'),
    status: Joi.string().valid('active', 'on-leave', 'suspended', 'resigned', 'retired'),
    highest_qualification: Joi.string().allow('', null),
    qualifications: Joi.array().items(Joi.object({
      degree: Joi.string().required(),
      institution: Joi.string().required(),
      year: Joi.number().required(),
      specialization: Joi.string().allow('', null)
    })),
    specialization: Joi.string().allow('', null),
    experience_years: Joi.number().min(0).allow(null),
    previous_experience: Joi.string().allow('', null),
    basic_salary: Joi.number().min(0).allow(null),
    gross_salary: Joi.number().min(0).allow(null),
    bank_name: Joi.string().allow('', null),
    bank_account_number: Joi.string().allow('', null),
    bank_ifsc: Joi.string().allow('', null),
    pf_number: Joi.string().allow('', null),
    esi_number: Joi.string().allow('', null),
    photo_url: Joi.string().allow('', null),
    resume_url: Joi.string().allow('', null),
    documents: Joi.array().items(Joi.object({
      type: Joi.string().required(),
      url: Joi.string().required(),
      name: Joi.string().required()
    })),
    emergency_contact_name: Joi.string().allow('', null),
    emergency_contact_phone: Joi.string().allow('', null),
    emergency_contact_relation: Joi.string().allow('', null),
    medical_conditions: Joi.string().allow('', null),
    allergies: Joi.string().allow('', null),
    subjects_can_teach: Joi.array().items(Joi.string()),
    notes: Joi.string().allow('', null)
  }).min(1),

  query: Joi.object({
    page: Joi.number().min(1).default(1),
    limit: Joi.number().min(1).max(100).default(50),
    search: Joi.string().allow(''),
    staff_type: Joi.string().valid('teaching', 'non-teaching', 'administrative', 'support'),
    department: Joi.string(),
    designation: Joi.string(),
    status: Joi.string().valid('active', 'on-leave', 'suspended', 'resigned', 'retired'),
    employment_type: Joi.string().valid('permanent', 'contract', 'temporary', 'part-time')
  })
};
